version: "3.8"


services:
  study_gram:
    container_name: study_gram
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./static/:/app/static/
      - ./media/:/app/media/
    ports:
        - "8000:8000"
